apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app.kubernetes.io/name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-app
    spec:
      containers:
      - name: flask-app
        image: {image}:{tag}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-serivce
spec:
  selector:
    app.kubernetes.io/name: flask
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501